-- This module serves as the root of the `Proof` library.
-- Import modules here that should be built as part of the library.
import Proof.Basic
import Simplex.Funs -- generated by `make lean` (imports Simplex.Types transitively)
