-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simplex]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Simplex.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open simplex

/-- [core::array::{core::hash::Hash for [T; N]}::hash]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 348:4-348:50
    Name pattern: [core::array::{core::hash::Hash<[@T; @N]>}::hash]
    Visibility: public -/
@[rust_fun "core::array::{core::hash::Hash<[@T; @N]>}::hash"]
axiom Array.Insts.CoreHashHash.hash
  {T : Type} {H : Type} {N : Std.Usize} (hashHashInst : core.hash.Hash T)
  (hashHasherInst : core.hash.Hasher H) :
  Array T N → H → Result H

/-- [core::array::{core::cmp::PartialOrd<[T; N]> for [T; N]}::partial_cmp]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 410:4-410:61
    Name pattern: [core::array::{core::cmp::PartialOrd<[@T; @N], [@T; @N]>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::array::{core::cmp::PartialOrd<[@T; @N], [@T; @N]>}::partial_cmp"]
axiom Array.Insts.CoreCmpPartialOrdArray.partial_cmp
  {T : Type} {N : Std.Usize} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Array T N → Array T N → Result (Option Ordering)

/-- [core::array::{core::cmp::Ord for [T; N]}::cmp]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 435:4-435:45
    Name pattern: [core::array::{core::cmp::Ord<[@T; @N]>}::cmp]
    Visibility: public -/
@[rust_fun "core::array::{core::cmp::Ord<[@T; @N]>}::cmp"]
axiom Array.Insts.CoreCmpOrd.cmp
  {T : Type} {N : Std.Usize} (cmpOrdInst : core.cmp.Ord T) :
  Array T N → Array T N → Result Ordering

/-- [core::borrow::{core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::cmp::impls::{core::cmp::Eq for u8}::assert_receiver_is_total_eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1898:12-1898:32
    Name pattern: [core::cmp::impls::{core::cmp::Eq<u8>}::assert_receiver_is_total_eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::impls::{core::cmp::Eq<u8>}::assert_receiver_is_total_eq"]
axiom U8.Insts.CoreCmpEq.assert_receiver_is_total_eq : Std.U8 → Result Unit

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2466:4-2473:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2485:4-2494:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish"]
axiom core.fmt.Formatter.debug_struct_field3_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::hash::impls::{core::hash::Hash for u8}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u8>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u8>}::hash"]
axiom U8.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U8 → H → Result H

/-- [core::hash::impls::{core::hash::Hash for u64}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u64>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u64>}::hash"]
axiom U64.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U64 → H → Result H

/-- [core::option::{core::fmt::Debug for core::option::Option<T>}::fmt]:
    Source: '/rustc/library/core/src/option.rs', lines 594:15-594:20
    Name pattern: [core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt]
    Visibility: public -/
@[rust_fun "core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt"]
axiom core.option.Option.Insts.CoreFmtDebug.fmt
  {T : Type} (fmtDebugInst : core.fmt.Debug T) :
  Option T → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::option::{core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2261:4-2261:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
axiom core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [core::option::{core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}::eq]:
    Source: '/rustc/library/core/src/option.rs', lines 2424:4-2424:38
    Name pattern: [core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq"]
axiom core.option.Option.Insts.CoreCmpPartialEqOption.eq
  {T : Type} (cmpPartialEqInst : core.cmp.PartialEq T T) :
  Option T → Option T → Result Bool

/-- [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, K, V, A>[TraitClause@2]}::or_insert]:
    Source: '/rustc/library/alloc/src/collections/btree/map/entry.rs', lines 161:4-161:51
    Name pattern: [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, @K, @V, @A>}::or_insert]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, @K, @V, @A>}::or_insert"]
axiom alloc.collections.btree.map.entry.Entry.or_insert
  {K : Type} {V : Type} {A : Type} (corecmpOrdInst : core.cmp.Ord K)
  (corecloneCloneInst : core.clone.Clone A) :
  alloc.collections.btree.map.entry.Entry K V corecloneCloneInst → V →
    Result (V × (V → Unit))

/-- [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, K, V, A>[TraitClause@3]}::or_default]:
    Source: '/rustc/library/alloc/src/collections/btree/map/entry.rs', lines 314:4-314:40
    Name pattern: [alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, @K, @V, @A>}::or_default]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::entry::{alloc::collections::btree::map::entry::Entry<'a, @K, @V, @A>}::or_default"]
axiom alloc.collections.btree.map.entry.Entry.or_default
  {K : Type} {V : Type} {A : Type} (corecmpOrdInst : core.cmp.Ord K)
  (coredefaultDefaultInst : core.default.Default V) (corecloneCloneInst :
  core.clone.Clone A) :
  alloc.collections.btree.map.entry.Entry K V corecloneCloneInst → Result (V
    × (V → Unit))

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, alloc::alloc::Global>[alloc::alloc::{core::clone::Clone for alloc::alloc::Global}]}::new]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 651:4-651:40
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>}::new]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>}::new"]
axiom alloc.collections.btree.map.BTreeMapKVGlobal.new
  (K : Type) (V : Type) :
  Result (alloc.collections.btree.map.BTreeMap K V core.core.clone.CloneGlobal)

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, A>[TraitClause@1]}::entry]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 1343:4-1345:15
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::entry]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::entry"]
axiom alloc.collections.btree.map.BTreeMap.entry
  {K : Type} {V : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A)
  (corecmpOrdInst : core.cmp.Ord K) :
  alloc.collections.btree.map.BTreeMap K V corecloneCloneInst → K → Result
    ((alloc.collections.btree.map.entry.Entry K V corecloneCloneInst) ×
    (alloc.collections.btree.map.BTreeMap K V corecloneCloneInst))

/-- [alloc::collections::btree::map::{core::default::Default for alloc::collections::btree::map::BTreeMap<K, V, alloc::alloc::Global>[alloc::alloc::{core::clone::Clone for alloc::alloc::Global}]}::default]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 2439:4-2439:34
    Name pattern: [alloc::collections::btree::map::{core::default::Default<alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>>}::default]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{core::default::Default<alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>>}::default"]
axiom
  alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreDefaultDefault.default
  (K : Type) (V : Type) :
  Result (alloc.collections.btree.map.BTreeMap K V core.core.clone.CloneGlobal)

/-- [alloc::collections::btree::map::{core::ops::index::Index<&0 (Q), V> for alloc::collections::btree::map::BTreeMap<K, V, A>[TraitClause@1]}::index]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 2491:4-2491:34
    Name pattern: [alloc::collections::btree::map::{core::ops::index::Index<alloc::collections::btree::map::BTreeMap<@K, @V, @A>, &'0 @Q, @V>}::index]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{core::ops::index::Index<alloc::collections::btree::map::BTreeMap<@K, @V, @A>, &'0 @Q, @V>}::index"]
axiom
  alloc.collections.btree.map.BTreeMap.Insts.CoreOpsIndexIndexShared0QV.index
  {K : Type} {Q : Type} {V : Type} {A : Type} (corecloneCloneInst :
  core.clone.Clone A) (coreborrowBorrowInst : core.borrow.Borrow K Q)
  (corecmpOrdInst : core.cmp.Ord K) (corecmpOrdInst1 : core.cmp.Ord Q) :
  alloc.collections.btree.map.BTreeMap K V corecloneCloneInst → Q → Result
    V

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, A>[TraitClause@1]}::len]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 2665:4-2665:36
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::len]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::len"]
axiom alloc.collections.btree.map.BTreeMap.len
  {K : Type} {V : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A) :
  alloc.collections.btree.map.BTreeMap K V corecloneCloneInst → Result
    Std.Usize

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, alloc::alloc::Global>[alloc::alloc::{core::clone::Clone for alloc::alloc::Global}]}::new]:
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 344:4-344:37
    Name pattern: [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, alloc::alloc::Global>}::new]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, alloc::alloc::Global>}::new"]
axiom alloc.collections.btree.set.BTreeSetTGlobal.new
  (T : Type) :
  Result (alloc.collections.btree.set.BTreeSet T core.core.clone.CloneGlobal)

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, A>[TraitClause@1]}::insert]:
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 898:4-900:15
    Name pattern: [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::insert"]
axiom alloc.collections.btree.set.BTreeSet.insert
  {T : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A)
  (corecmpOrdInst : core.cmp.Ord T) :
  alloc.collections.btree.set.BTreeSet T corecloneCloneInst → T → Result
    (Bool × (alloc.collections.btree.set.BTreeSet T corecloneCloneInst))

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, A>[TraitClause@1]}::iter]:
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 1243:4-1243:37
    Name pattern: [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::iter]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::iter"]
axiom alloc.collections.btree.set.BTreeSet.iter
  {T : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A) :
  alloc.collections.btree.set.BTreeSet T corecloneCloneInst → Result
    (alloc.collections.btree.set.Iter T)

/-- [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<T, A>[TraitClause@1]}::is_empty]:
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 1290:4-1290:40
    Name pattern: [alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::is_empty]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::set::{alloc::collections::btree::set::BTreeSet<@T, @A>}::is_empty"]
axiom alloc.collections.btree.set.BTreeSet.is_empty
  {T : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A) :
  alloc.collections.btree.set.BTreeSet T corecloneCloneInst → Result Bool

/-- [alloc::collections::btree::set::{core::iter::traits::iterator::Iterator<&'a (T)> for alloc::collections::btree::set::Iter<'a, T>}::next]:
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 1761:4-1761:39
    Name pattern: [alloc::collections::btree::set::{core::iter::traits::iterator::Iterator<alloc::collections::btree::set::Iter<'a, @T>, &'a @T>}::next]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::set::{core::iter::traits::iterator::Iterator<alloc::collections::btree::set::Iter<'a, @T>, &'a @T>}::next"]
axiom
  alloc.collections.btree.set.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next
  {T : Type} :
  alloc.collections.btree.set.Iter T → Result ((Option T) ×
    (alloc.collections.btree.set.Iter T))

/-- [alloc::vec::{core::iter::traits::collect::Extend<T> for alloc::vec::Vec<T>}::extend]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3867:4-3867:60
    Name pattern: [alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend"]
axiom alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend.extend
  {T : Type} (A : Type) {I : Type} {Clause1_IntoIter : Type}
  (coreitertraitscollectIntoIteratorInst :
  core.iter.traits.collect.IntoIterator I T Clause1_IntoIter) :
  alloc.vec.Vec T → I → Result (alloc.vec.Vec T)

/-- [simplex::consensus::{core::cmp::PartialEq<simplex::consensus::Event> for simplex::consensus::Event}::ne]:
    Source: 'src/consensus.rs', lines 6:16-6:25
    Visibility: public -/
axiom consensus.Event.Insts.CoreCmpPartialEqEvent.ne
  : consensus.Event → consensus.Event → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::TimerId> for simplex::types::TimerId}::ne]:
    Source: 'src/types.rs', lines 51:29-51:38
    Visibility: public -/
axiom types.TimerId.Insts.CoreCmpPartialEqTimerId.ne
  : types.TimerId → types.TimerId → Result Bool

/-- [simplex::message::{core::cmp::PartialEq<simplex::message::Message> for simplex::message::Message}::ne]:
    Source: 'src/message.rs', lines 23:23-23:32
    Visibility: public -/
axiom message.Message.Insts.CoreCmpPartialEqMessage.ne
  : message.Message → message.Message → Result Bool

/-- [simplex::message::{core::cmp::PartialEq<simplex::message::Finalize> for simplex::message::Finalize}::ne]:
    Source: 'src/message.rs', lines 17:23-17:32
    Visibility: public -/
axiom message.Finalize.Insts.CoreCmpPartialEqFinalize.ne
  : message.Finalize → message.Finalize → Result Bool

/-- [simplex::message::{core::cmp::PartialEq<simplex::message::Vote> for simplex::message::Vote}::ne]:
    Source: 'src/message.rs', lines 9:23-9:32
    Visibility: public -/
axiom message.Vote.Insts.CoreCmpPartialEqVote.ne
  : message.Vote → message.Vote → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::BlockHash> for simplex::types::BlockHash}::ne]:
    Source: 'src/types.rs', lines 20:29-20:38
    Visibility: public -/
axiom types.BlockHash.Insts.CoreCmpPartialEqBlockHash.ne
  : types.BlockHash → types.BlockHash → Result Bool

/-- [simplex::message::{core::cmp::PartialEq<simplex::message::Proposal> for simplex::message::Proposal}::ne]:
    Source: 'src/message.rs', lines 3:23-3:32
    Visibility: public -/
axiom message.Proposal.Insts.CoreCmpPartialEqProposal.ne
  : message.Proposal → message.Proposal → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::TransactionHash> for simplex::types::TransactionHash}::ne]:
    Source: 'src/types.rs', lines 23:29-23:38
    Visibility: public -/
axiom types.TransactionHash.Insts.CoreCmpPartialEqTransactionHash.ne
  : types.TransactionHash → types.TransactionHash → Result Bool

/-- [simplex::consensus::{core::cmp::PartialEq<simplex::consensus::Action> for simplex::consensus::Action}::ne]:
    Source: 'src/consensus.rs', lines 12:16-12:25
    Visibility: public -/
axiom consensus.Action.Insts.CoreCmpPartialEqAction.ne
  : consensus.Action → consensus.Action → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::Block> for simplex::types::Block}::ne]:
    Source: 'src/types.rs', lines 27:23-27:32
    Visibility: public -/
axiom types.Block.Insts.CoreCmpPartialEqBlock.ne
  : types.Block → types.Block → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::PeerId> for simplex::types::PeerId}::ne]:
    Source: 'src/types.rs', lines 3:29-3:38
    Visibility: public -/
axiom types.PeerId.Insts.CoreCmpPartialEqPeerId.ne
  : types.PeerId → types.PeerId → Result Bool

/-- [simplex::types::{core::cmp::PartialEq<simplex::types::View> for simplex::types::View}::ne]:
    Source: 'src/types.rs', lines 6:29-6:38
    Visibility: public -/
axiom types.View.Insts.CoreCmpPartialEqView.ne
  : types.View → types.View → Result Bool
