-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [simplex]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [alloc::collections::btree::map::entry::OccupiedEntry]
    Source: '/rustc/library/alloc/src/collections/btree/map/entry.rs', lines 75:0-80:1
    Name pattern: [alloc::collections::btree::map::entry::OccupiedEntry]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::entry::OccupiedEntry"]
axiom alloc.collections.btree.map.entry.OccupiedEntry (K : Type) (V : Type) {A
  : Type} (corecloneCloneInst : core.clone.Clone A) : Type

/-- [alloc::collections::btree::map::entry::VacantEntry]
    Source: '/rustc/library/alloc/src/collections/btree/map/entry.rs', lines 47:0-52:1
    Name pattern: [alloc::collections::btree::map::entry::VacantEntry]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::entry::VacantEntry"]
axiom alloc.collections.btree.map.entry.VacantEntry (K : Type) (V : Type) {A :
  Type} (corecloneCloneInst : core.clone.Clone A) : Type

/-- [alloc::collections::btree::map::BTreeMap]
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 189:0-193:1
    Name pattern: [alloc::collections::btree::map::BTreeMap]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::BTreeMap"]
axiom alloc.collections.btree.map.BTreeMap (K : Type) (V : Type) {A : Type}
  (corecloneCloneInst : core.clone.Clone A) : Type
